### ISSUE TITLE
GPT controller is incompatible with AdSense

### ISSUE THREAD

**Issue by CarloCannas** [PubMatic/OpenWrap#159]
If AdSense is loaded in the page it may interfere with the loading of the GPT controller: the controller might think googletag already loaded and stop the initialization.

The GPT controller [needs to be initialized before `gpt.js` loads](https://github.com/PubMatic/OpenWrap/blob/v19.2.0_NIGHTLY/src_new/controllers/gpt.js#L825-L859) in order to monkey-patch the `gpt` object and intercept every ad request.

Some checks are performed to determine if `gpt.js` is loaded at the controller initialization: here [the problematic one is `util.isUndefined(win.google_onload_fired)`](https://github.com/PubMatic/OpenWrap/blob/v19.2.0_NIGHTLY/src_new/controllers/gpt.js#L843).

`window.google_onload_fired` is not only set by `gpt.js`  but is also set by Google AdSense during its loading, so if an AdSense ad code is present on the page and it gets to load before `pwt.js`, the GPT controller won't be able to initialize and no prebid will be performed for that pageview.

More specifically, `google_onload_fired` is set (at the time of writing) by the script https://pagead2.googlesyndication.com/pagead/js/r20200422/r20190131/show_ads_impl_fy2019.js, which is loaded by the main script https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js as soon as an ad request is performed (i.e. a call to `adsbygoogle.push({})`) or just as the main script loads if the page uses the [new auto ad code](https://support.google.com/adsense/answer/9274634) (the one with the `data-ad-client` attribute on the `script` element: `<script data-ad-client="ca-pub-1234567890123456" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>`).

I think this incompatibility should be at least documented: one might setup `pwt.js` in a page with AdSense ad units and the prebid might even work properly during testing but since the scripts loading is asynchronous there's effectively a race and on some devices, network and cache conditions AdSense might load before `pwt.js` and inhibit it.

Of course all this can be avoided using the custom contoller which doesn't monkey-patch GPT.

However, couldn't the `google_onload_fired` check be removed entirely? The other checks in that condition look sufficient to me: `googletag.cmd` stays an array until GPT is initialized and after that `googletag.cmd.unshift` doesn't even exist anymore. So why the need of checking the existance of `google_onload_fired`?

**Comment by mike-chowla** [comment]
@CarloCannas Thank you for the detailed issue write up.  I've confirmed the issue with our engineering team and we'll address this in an upcoming release

**Comment by pm-shashank-jain** [comment]
Issue is fixed in Release https://github.com/PubMatic/OpenWrap/releases/tag/v19.7.0_NIGHTLY
