### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by progix21** [PubMatic/OpenWrap#206]
Hi Team,

I have started building the Openwrap project with following steps, but getting an error while building:
OS: Linux 
Node Version: v10.22.1
NPM Version: 6.14.6
Prebid Version: 1.9.0

Requirements:
npm install -g gulp gulp-cli yargs shelljs # Please include yargs and shelljs in README.md
npm install # In Folder
./build.sh --mode=test-build --prebidpath=../Prebid/ # Prebid path is correct

Error:
Not Found - GET https://registry.npmjs.org/uas-adclient - Not found

Please help with resolution of this error and update README.md as required.

-Priyesh

**Comment by pm-shashank-jain** [comment]
Hi Priyesh,

UAS-AdClient was an internal dependency and currently deprecated. Please remove this from package.json for now. It will soon be removed.
