### ISSUE TITLE
Support prebid.js instant load

### ISSUE THREAD

**Issue by micke239** [PubMatic/OpenWrap#23]
This feature would improve first render time and viewability.

http://prebid.org/blog/dfp-instant-load

**Comment by pm-abhinav-sinha** [comment]
@micke239 OpenWrap from inception relies on GPT execution and intercepts real time GPT events so there is no unnecessary blocking of GPT. You can refer to the sample page https://github.com/PubMatic/OpenWrap/blob/master/sample_pages/WTAsyncDemo.html. 
The only requirement is : GPT library load needs to happen after OpenWrap js library. I believe the root of confusion is jsLoaded callback function seems similar to Prebid post  auction callback function on page whereas it is just library load notification.

**Comment by JustinGaravel** [comment]
@pm-abhinav-sinha 
> I believe the root of confusion is jsLoaded callback function seems similar to Prebid post auction callback function on page whereas it is just library load notification.

Thanks for your comment this helped me a bit. Do you have a link to where this is documented? Assume this is right but the comments in the sample code is cryptic.

**Comment by pm-harshad-mane** [comment]
Hello @JustinGaravel ,
You can refer to https://github.com/PubMatic/OpenWrap/blob/master/sample_pages/WTAsyncDemo.html
